# Generated by Django 3.2 on 2021-05-15 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0003_alter_car_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='tour',
        ),
    ]
